/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class chem_ChemCalculation */

#ifndef _Included_chem_ChemCalculation
#define _Included_chem_ChemCalculation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     chem_ChemCalculation
 * Method:    calcChem
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_chem_ChemCalculation_calcChem
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
